### PR TITLE
CS140e: Assignment 0

### LINKED ISSUE #3: CS140e A0-P0
Complete CS140e Assignment 0 Phase 0. Copy starter code into this repository and document the process.

https://cs140e.sergio.bz/assignments/0-blinky/#phase-0-getting-started

### LINKED ISSUE #4: CS140e A0-P1
Complete CS140e Assignment 0 Phase 1. Write code in this repository and document the process.

https://cs140e.sergio.bz/assignments/0-blinky/#phase-1-baking-pi

### LINKED ISSUE #5: CS140e A0-P2
Complete CS140e Assignment 0 Phase 2. Write code in this repository and document the process.

https://cs140e.sergio.bz/assignments/0-blinky/#phase-2-led-there-be-light

### LINKED ISSUE #6: CS140e A0-P3
Complete CS140e Assignment 0 Phase 3. Write code in this repository and document the process.

https://cs140e.sergio.bz/assignments/0-blinky/#phase-3-shining-c

### LINKED ISSUE #7: CS140e A0-P4
Complete CS140e Assignment 0 Phase 4. Write code in this repository and document the process.

https://cs140e.sergio.bz/assignments/0-blinky/#phase-4-rusting-away

### PR DESCRIPTION
**Pull request by jaredtbates**
This PR includes Assignment 0. I will start it as a "Draft" PR, and push a commit for each Phase of the Assignment.

Since this has a lot of pre-written code (copied from CS140e), the main focus is on the documentation at `docs/cs140e/assignment-0.md`.

Closes #3
Closes #4
Closes #5
Closes #6
Closes #7

### CODE REVIEW

**Comment by lubaochuan** [comment]
Did you try to compile and test the code on your Pi? Could you document the steps you took to set up your development environment?

**Comment by jaredtbates** [comment]
@lubaochuan Please see the Markdown file here: https://github.com/computerwizjared/Capstone/pull/22/files#diff-1b8bcc73ab9f5d39c7369a8c8e0bdef6f97d92d13de4a96ee7cb81f2e03457bd

**Comment by jaredtbates** [comment]
I've finished up Assignment 0, all phases are committed now. Please take a look and let me know what you think! I encountered some issues towards the end of phase 4 because I upgraded Rust to the latest version, but got it all figured out.

**Comment by jaredtbates** [comment]
@lubaochuan Please give your approval on this (Assignment 0) when you are ready :) I have started a separate PR for Assignment 1.

**Comment by lubaochuan** [comment]
Sorry about the delay. Your work for assignment 0 looks good.

**Pull request merged**
